name: Build & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build1:
    name: Build
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Installing dependencies
        run: yarn --frozen-lockfile

      - name: Building project
        run: yarn run build

      - name: Running tests
        run: yarn run test

      - name: Uploading production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: dist
          if-no-files-found: error

  deploy:
    name: Deploy
    needs: build1
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v3
        with:
          name: Build
          path: dist

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: Build

      - name: Deploying to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          commit_message: ${{ github.event.head_commit.message }}
