name: Generate Changelog
on:
  release:
    types:
      - created
jobs:
  changelog:
    runs-on: macos-latest
    steps:
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
