name: Workflow-cleanup

on:
  push:

jobs:
  cleanup:
    name: Clean up
    runs-on: macos-latest
    permissions:
      actions: write
    timeout-minutes: 3
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: LinaWijkander/Recipes
          older-than-seconds: 604 
