name: Workflow-cleanup

on:
  push:

jobs:
  del-flow:
    name: Delete flows
    runs-on: macos-latest
    permissions:
      actions: write
    timeout-minutes: 3
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: LinaWijkander/Recipes
          retain_days: 7
          keep_minimum_runs: 3
